server:
  port: 64412

spring:
  application:
    name: auth-service

eureka:
  instance:
    instance-id: auth-microservice-instance

client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
