server:
  port: 8000

eureka:
  instance:
    instance-id: gateway-microservice-instance

client:
  register-with-eureka: true
  fetch-registry: true
  service-url:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          #uri: http://localhost:64412 # 포워딩할 주소, http://localhost:8000/auth 로 들어오면 http://localhost:64412 로 포워딩
          predicates:
            - Path=/auth/** # 해당 gateway 서버의 /auth/**로 들어오는 요은 auth-service로 인식하겠다는 조건
          filters:
            - RewritePath=/auth/?(?<segment>.*), /$\{segment}

        - id: push-service
          uri: lb://PUSH-SERVICE
          #uri: http://localhost:54412 # 포워딩 할 주소, http://localhost:8000/push 로 들어오면 http://localhost:54412 로 포워딩
          predicates:
            - Path=/push/** # 해당 gateway 서버의 /push/**로 들어오는 요은 order-service로 인식하겠다는 조건
          filters:
            - RewritePath=/push/?(?<segment>.*), /$\{segment}
